create table if not exists qa_audit (
  id bigint generated by default as identity primary key,
  session_id varchar(128) not null,
  question clob not null,
  source varchar(32) not null,
  uncertain boolean not null,
  cache_hit boolean not null,
  created_at timestamp default current_timestamp not null
);
